export const EXPLANATIONS = Object.freeze({
  ready: 'まだ計算は始まっていません。現在の入力とパラメータが、この実験の出発点です。',
  input: '入力は現実の特徴を数値へ置き換えたものです。この小型ネットワークでは5個の値を一つの入力ベクトルとして扱います。',
  'weighted-product': '重みは接続ごとの影響の向きと強さです。正なら同じ向き、負なら反対向きへ入力を作用させます。',
  'weighted-sum': '重み付き和は、各入力と重みの積を合計した値です。バイアスは入力が0でもノードが反応できるよう、最後に足す調整値です。',
  activation: '活性化関数tanhは重み付き和を-1から+1へ圧縮します。これにより、単純な直線計算では表せない変化を作れます。',
  logit: 'logitはsoftmaxへ入れる前の生の得点です。まだ確率ではなく、負の値や合計が1でない値も取ります。',
  softmax: 'softmaxは3個のlogitを、すべて0以上で合計1になる確率へ変換します。最大値を先に引くのは指数計算の桁あふれを防ぐためです。',
  argmax: 'argmaxは最も大きい値の位置を返します。初版は確率的に抽選せず、最大確率をそのまま判断にします。',
  'one-hot': 'one-hotベクトルは正解クラスだけが1で、他が0の教師信号です。予測確率との差をクラスごとに計算できます。',
  loss: '損失関数は予測の誤りを一つの数値にまとめます。クロスエントロピーは正解確率が低いほど大きくなります。',
  'output-error': '出力誤差は、各logitを少し動かしたとき損失がどう変わるかを表します。ここから逆向きの計算が始まります。',
  gradient: '勾配は、そのパラメータをわずかに増やしたとき損失が増える向きと強さです。負なら増やすことで損失が下がる方向を示します。',
  backpropagation: '誤差逆伝播は、出力側で分かった誤差を接続の重みと局所微分を使って入力側へ配分する計算方法です。',
  'activation-derivative': 'tanhの微分は、その場所で活性値が変化しやすいかを示します。±1付近では傾きが小さく、0付近では大きくなります。',
  update: '学習率は一回の更新幅を調整します。大きすぎると最小値を飛び越すことがあり、小さすぎると変化が見えにくくなります。',
  recompute: '更新したネットワークへ同じ入力を通し直すことで、学習が次回の出力をどう変えたかを直接確認します。',
  comparison: '一件の入力を一回学習した結果です。通常は正解確率が上がりますが、極端な学習率では損失が増える可能性もあります。',
  learning: '一回の学習では、順伝播、損失、逆伝播、更新を一組として実行します。',
});

export const RL_GLOSSARY = Object.freeze([
  {
    key: 'observation', term: '観測（Observation）', level: 1,
    definition: 'AIが行動を決める前に、いまの周囲を数値として受け取ること。',
    location: '盤面と「観測」ステップ', stage: 'rl-observation',
    focus: '#rl-grid-board', highlights: ['#rl-grid-board', '[data-rl-axis="observe"]'],
  },
  {
    key: 'policy', term: '方策（Policy）', level: 1,
    definition: 'いまの場面で、それぞれの行動をどれくらい選びやすいかを表すもの。',
    location: '3本の行動バー', stage: 'rl-policy',
    focus: '#rl-policy-bars .rl-policy-row', highlights: ['#rl-policy-bars', '[data-rl-axis="policy"]'],
  },
  {
    key: 'reward', term: '報酬（Reward）', level: 1,
    definition: '実際に行動した直後の結果を、良かった・悪かったの数値で表したもの。',
    location: '行動履歴の報酬列', stage: 'rl-transition',
    focus: '#rl-experience-body tr.active td:nth-child(7)', highlights: ['#rl-experience-body tr.active', '#rl-experience-body tr.active td:nth-child(7)', '[data-rl-axis="transition"]'],
  },
  {
    key: 'sampling', term: 'サンプリング（Sampling）', level: 2,
    definition: '選びやすさの割合を使い、実際に試す行動を1つ選ぶこと。',
    location: '「行動を選ぶ」ステップ', stage: 'rl-sample',
    focus: '#rl-policy-bars .rl-policy-row.selected', highlights: ['#rl-policy-bars', '[data-rl-axis="sample"]'],
  },
  {
    key: 'return', term: 'リターン（Return）', level: 2,
    definition: 'その時点より後でもらった報酬を、近い結果ほど重くしてまとめた値。',
    location: '行動履歴のリターン列', stage: 'rl-return',
    focus: '#rl-experience-body tr.active td:last-child', highlights: ['#rl-experience-body tr.active', '#rl-experience-body tr.active td:last-child', '[data-rl-axis="return"]'],
  },
  {
    key: 'policy-gradient', term: '方策勾配（Policy Gradient）', level: 3,
    definition: '得られた結果を使って、行動の選びやすさをどちらへ直すか計算した値。',
    location: '「直し方を計算」ステップ', stage: 'rl-gradient',
    focus: '#rl-formula', highlights: ['#rl-formula', '[data-rl-axis="gradient"]'],
  },
  {
    key: 'learning-rate', term: '学習率（Learning Rate）', level: 3,
    definition: '内部の数字を1回でどれくらい大きく直すかを決める値。',
    location: '39個の更新表', stage: 'rl-update',
    focus: '#rl-parameter-body tr.active', highlights: ['#rl-parameter-body tr.active', '[data-rl-axis="update"]'],
  },
]);
