export const EXPLANATIONS = Object.freeze({
  ready: 'まだ計算は始まっていません。現在の入力とパラメータが、この実験の出発点です。',
  input: '入力は現実の特徴を数値へ置き換えたものです。この小型ネットワークでは5個の値を一つの入力ベクトルとして扱います。',
  'weighted-product': '重みは接続ごとの影響の向きと強さです。正なら同じ向き、負なら反対向きへ入力を作用させます。',
  'weighted-sum': '重み付き和は、各入力と重みの積を合計した値です。バイアスは入力が0でもノードが反応できるよう、最後に足す調整値です。',
  activation: '活性化関数tanhは重み付き和を-1から+1へ圧縮します。これにより、単純な直線計算では表せない変化を作れます。',
  logit: 'logitはsoftmaxへ入れる前の生の得点です。まだ確率ではなく、負の値や合計が1でない値も取ります。',
  softmax: 'softmaxは3個のlogitを、すべて0以上で合計1になる確率へ変換します。最大値を先に引くのは指数計算の桁あふれを防ぐためです。',
  argmax: 'argmaxは最も大きい値の位置を返します。初版は確率的に抽選せず、最大確率をそのまま判断にします。',
  'one-hot': 'one-hotベクトルは正解クラスだけが1で、他が0の教師信号です。予測確率との差をクラスごとに計算できます。',
  loss: '損失関数は予測の誤りを一つの数値にまとめます。クロスエントロピーは正解確率が低いほど大きくなります。',
  'output-error': '出力誤差は、各logitを少し動かしたとき損失がどう変わるかを表します。ここから逆向きの計算が始まります。',
  gradient: '勾配は、そのパラメータをわずかに増やしたとき損失が増える向きと強さです。負なら増やすことで損失が下がる方向を示します。',
  backpropagation: '誤差逆伝播は、出力側で分かった誤差を接続の重みと局所微分を使って入力側へ配分する計算方法です。',
  'activation-derivative': 'tanhの微分は、その場所で活性値が変化しやすいかを示します。±1付近では傾きが小さく、0付近では大きくなります。',
  update: '学習率は一回の更新幅を調整します。大きすぎると最小値を飛び越すことがあり、小さすぎると変化が見えにくくなります。',
  recompute: '更新したネットワークへ同じ入力を通し直すことで、学習が次回の出力をどう変えたかを直接確認します。',
  comparison: '一件の入力を一回学習した結果です。通常は正解確率が上がりますが、極端な学習率では損失が増える可能性もあります。',
  learning: '一回の学習では、順伝播、損失、逆伝播、更新を一組として実行します。',
});

export const GLOSSARY = Object.freeze([
  { key: 'input', term: '入力', level: 1, definition: 'AIへ最初に渡す数字。この実験では5個あります。', location: '左の入力操作と、図のI1〜I5です。', stage: 'input', focus: '#network-svg [data-node="input-0"]', highlights: ['#network-svg [data-node^="input-"]'] },
  { key: 'node', term: 'ノード（Node）', level: 1, definition: '入ってきた数字を計算し、次へ渡す場所です。', location: '丸で描かれたI、H、Oです。', stage: 'hidden-sum', focus: '#network-svg .network-node.active', highlights: ['#network-svg .network-node.active'] },
  { key: 'weight', term: '重み（Weight）', level: 1, definition: '数字を次へどのくらい強く伝えるかを決める値です。', location: 'ノードを結ぶ線と、同じ名前のParameter行です。', stage: 'update-weight', requiresLearning: true, focus: '#network-svg .network-connection.active', highlights: ['#network-svg .network-connection.active', '#parameter-body tr.active', '#formula-display'] },
  { key: 'weighted-sum', term: '重み付き和', level: 2, definition: '入力と線の強さを掛けた結果を集め、調整値を足した数字です。', location: 'Hノードのzと計算式です。', stage: 'hidden-sum', focus: '#network-svg .network-node.active', highlights: ['#network-svg .network-node.active', '#formula-display'] },
  { key: 'bias', term: 'バイアス（Bias）', level: 2, definition: '集めた数字へ最後に足す、ノードごとの調整値です。', location: '計算式とParameter表のbから始まる行です。', stage: 'update-bias', requiresLearning: true, focus: '#parameter-body tr.active', highlights: ['#parameter-body tr.active', '#formula-display'] },
  { key: 'activation', term: '活性化関数', level: 2, definition: '集めた数字を、次へ渡しやすい範囲へ変える計算です。', location: 'Hノードのaとtanhの計算式です。', stage: 'tanh', focus: '#network-svg .network-node.active', highlights: ['#network-svg .network-node.active', '#formula-display'] },
  { key: 'logit', term: 'logit', level: 2, definition: 'どの答えを選びそうかを表す、確率へ変える前の得点です。', location: 'Oノードのlogitです。', stage: 'logit', focus: '#network-svg .network-node.active', highlights: ['#network-svg .network-node.active', '#formula-display'] },
  { key: 'softmax', term: 'softmax／確率', level: 2, definition: '複数の得点を、合計100%の選ばれやすさへ変える計算です。', location: 'Oノードのpと右側の出力summaryです。', stage: 'softmax', focus: '#network-svg .network-node.active', highlights: ['#network-svg .network-node.active', '#output-summary', '#formula-display'] },
  { key: 'loss', term: '損失（Loss）', level: 2, definition: '予測が正解からどのくらい外れたかを、一つにまとめた数字です。', location: '学習timelineの「ずれを測る」段階と計算式です。', stage: 'loss', requiresLearning: true, focus: '#formula-display', highlights: ['#formula-display', '#step-title'] },
  { key: 'gradient', term: '勾配（Gradient）', level: 3, definition: '内部の数字をどちらへ動かすと、失敗が減るかを示す値です。', location: '強調された線、Parameter行、計算式です。', stage: 'gradient-ho', requiresLearning: true, focus: '#network-svg .network-connection.active', highlights: ['#network-svg .network-connection.active', '#parameter-body tr.active', '#formula-display'] },
  { key: 'backpropagation', term: '誤差逆伝播', level: 3, definition: '答え側で分かった失敗を、前の計算へ順番に戻す方法です。', location: '出力の誤差からHノードへ戻るtimelineです。', stage: 'output-error', requiresLearning: true, focus: '#network-svg .network-node.active', highlights: ['#network-svg .network-node.active', '#formula-display'] },
  { key: 'learning-rate', term: '学習率（Learning Rate）', level: 3, definition: '1回で内部の数字をどのくらい大きく直すかを決める値です。', location: '実験条件の入力欄とParameter更新式です。', stage: 'update-weight', requiresLearning: true, focus: '#learning-rate', highlights: ['#learning-rate', '#formula-display'] },
]);
